apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: visma.localhost
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: svc
            port:
              name: http