apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: visma-
commonLabels:
  app: visma-sre
resources:
- deployment.yml
- service.yml
- ingress.yml
- ingress-local.yml
- monitor.yml
images:
- name: dagandersen/visma-sre
  newTag: "4312901798"
