apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor
  namespace: prometheus
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: visma-sre
  endpoints:
  - port: http
  namespaceSelector:
    any: true