apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prometheus-local  
  namespace: prometheus
spec:
  rules:
  - host: prometheus.localhost
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: prometheus-grafana
              port:
                number: 3000