apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: flux-system
spec:
  rules:
  - host: flux.localhost
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001