apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/visma-e-conomic-hiring
    targetRevision: HEAD
    path: ./k8s/argo-config
  syncPolicy: 
    automated:
      prune: true