apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-pdf-or-png
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/visma-e-conomic-hiring
    targetRevision: HEAD
    path: ./argo/dummy-pdf-or-png
  syncPolicy: 
    automated:
      prune: true