apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello-world-
commonLabels:
  app: hello-world
resources:
- deployment.yml

images:
- name: dagandersen/hello-world
  newTag: prod-d50c64db-1690709830
