apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello-world-
commonLabels:
  app: hello-world
resources:
- deployment.yml
- image-repository.yml
- image-policy.yml
images:
- name: dagandersen/hello-world
  newTag: prod-bd944f87-1692432327
